apiVersion: v1
kind: ServiceAccount
metadata:
  name: cerberus-orchestrator
  namespace: cerberus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cerberus-orchestrator
  namespace: cerberus
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "delete", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cerberus-orchestrator
  namespace: cerberus
subjects:
  - kind: ServiceAccount
    name: cerberus-orchestrator
    namespace: cerberus
roleRef:
  kind: Role
  name: cerberus-orchestrator
  apiGroup: rbac.authorization.k8s.io
